name: Build and Release Go Client

on:
  push:
    tags:
      - 'client-v*'

jobs:
  build:
    name: Build Go Client
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Build release binaries
        run: |
          apt install libasound2-dev
          cd client
          make release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            client/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
