name: Build and Release Go Client

on:
  push:
    tags:
      - 'client-v*'

jobs:
  build:
    name: Build Go Client
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Install sound dependence (Linux only)
        run: sudo apt install -y libasound2-dev

      - name: Download latest homies-video-player release
        run: |
          curl -s https://api.github.com/repos/rbarjavel/homies_gaming_backend/releases > release_info.json
          WINDOWS_URL=$(cat release_info.json | jq -r '.[] | select(.assets[]?.name? | contains("homies-video-player-windows")) | .assets[] | select(.name | contains("homies-video-player-windows")) | .browser_download_url' | head -1)

          LINUX_URL=$(cat release_info.json | jq -r '.[] | select(.assets[]?.name? | contains("homies-video-player-linux")) | .assets[] | select(.name | contains("homies-video-player-linux")) | .browser_download_url' | head -1)

          # Download and extract releases
          mkdir -p client/godot_bin/windows
          mkdir -p client/godot_bin/linux
          mkdir -p temp_linux

          # Windows
          wget $WINDOWS_URL -O homies-windows.zip
          unzip homies-windows.zip -d temp_windows
          cp temp_windows/windows/* client/godot_bin/windows/
          rm -rf temp_windows homies-windows.zip

          # Linux
          wget $LINUX_URL -O homies-linux.tar.gz
          tar -xzf homies-linux.tar.gz -C temp_linux
          cp temp_linux/linux/* client/godot_bin/linux/
          rm -rf temp_linux homies-linux.tar.gz

      - name: Build release binaries
        run: |
          cd client
          make release

      - name: Archive live_chat for Linux
        run: |
          cd client
          mv bin/live_chat_linux .
          zip -r live_chat_linux.zip live_chat_linux godot_bin mpv

      - name: Archive live_chat for macOS
        run: |
          cd client
          mv bin/live_chat_macos .
          zip -r live_chat_macos.zip live_chat_macos godot_bin mpv

      - name: Archive live_chat for Windows
        run: |
          cd client
          mv bin/live_chat_windows.exe .
          zip -r live_chat_windows.zip live_chat_windows.exe godot_bin mpv

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            client/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
