name: Build Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: make release

      - name: Package binary
        run: |
          mkdir -p release
          cp target/release/homies_gaming_backend release/
          cp README.md release/ 2>/dev/null || echo "No README.md found"
          cp -r templates release/ 2>/dev/null || echo "No templates directory found"
          tar -czf homies-gaming-backend-linux-x86_64.tar.gz -C release .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./homies-gaming-backend-linux-x86_64.tar.gz
          asset_name: homies-gaming-backend-linux-x86_64.tar.gz
          asset_content_type: application/gzip
